# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
