# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.DateTimeField(verbose_name='Horario de Inicio')),
                ('horario_final', models.DateTimeField(verbose_name='Horario de Termino')),
                ('horario_entrada', models.DateTimeField(verbose_name='Horario Máximo de Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Morador')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Usuario'),
        ),
    ]
