# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171028_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8)),
                ('modelo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('cor_principal', models.CharField(max_length=30)),
                ('cor_secundaria', models.CharField(max_length=30)),
                ('convidado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Convidado')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='titulo',
            field=models.CharField(default='teste', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convidado',
            name='eventos',
            field=models.ManyToManyField(to='polls.Evento'),
        ),
    ]
